server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.64.128
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    database: 0
    host: 192.168.64.128
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.dong.server.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.dong.server.mapper: debug